# Site
title: ToDoList
subtitle: ''
description: 'Recently I started learning React and develope this sample To-Do List App.'
keywords:
author: Kimi
language: zh-TW
timezone: ''

url: https://a3216lucy.github.io/react-todo/
root: /public/


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: https://github.com/a3216lucy/react-todo/
  branch: gh-pages
