const todos = [
  {
    id: 1,
    title: 'Shopping',
    date: '2022-01-31',
    time: '18:30',
    comment: '',
    completed: false,
    important: false,
    isEditMode: false,
  },
  {
    id: 2,
    title: 'Reading',
    date: '2022-02-01',
    time: '10:20',
    comment: 'books list: Atomic Habits',
    completed: false,
    important: false,
    isEditMode: false,
  },
  {
    id: 3,
    title: 'Watch movies',
    date: '',
    time: '',
    comment: '',
    completed: true,
    important: false,
    isEditMode: false,
  },
  {
    id: 4,
    title: 'Buy comics',
    date: '2022-01-04',
    time: '',
    comment: 'Attack on Titan',
    completed: false,
    important: true,
    isEditMode: false,
  },
  {
    id: 5,
    title: 'Camping',
    date: '',
    time: '15:00',
    comment: 'with friends and bring some food.',
    completed: true,
    important: false,
    isEditMode: false,
  },
];

export default todos;
